version: 2.1

orbs:
  npm-publish: saildrone/npm-publish@0

jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:22.14.0

    steps:
      - checkout
      - npm-publish/npm-login
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: NPM Test
          command: npm test

workflows:
  test_and_publish:
    jobs:
      - test:
          context: platform-k8s
          filters:
            tags:
              only: /.*/
      - npm-publish/login-publish:
          image: cimg/node:22.14.0
          requires:
            - test
          context: platform-k8s
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
