version: 2.1

orbs:
  npm-github-publish: saildrone/npm-github-publish@0.1

jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.18.2

    steps:
      - checkout
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: NPM Test
          command: npm test

workflows:
  test_and_publish:
    jobs:
      - test:
          context: platform-k8s
          filters:
            tags:
              only: /.*/
      - npm-github-publish/login-publish:
          image: cimg/node:14.18.2
          requires:
            - test
          context: platform-k8s
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/