version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  sd-helpers: saildrone/sd-helpers@0.0.23
  npm-publish: saildrone/npm-publish@0.0.1

# commands:
#   install_prerequisites:
#     steps:
#       - run:
#           name: "Install prerequisites"
#           command: |
#             apt-get -y update
#             apt-get -y install curl
#             apt-get -y install unzip

jobs:
  test:
    working_directory: ~/app
    docker:
      - image: cimg/node:14.18.2

    steps:
      - checkout
      # - install_prerequisites
      - aws-cli/install
      - sd-helpers/get-aws-creds
      - sd-helpers/codeartifact-login
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: NPM Test
          command: npm test

workflows:
  test_and_publish:
    jobs:
      - test:
          context: platform-k8s
          filters:
            tags:
              only: /.*/
      - npm-github-publish/login-publish:
          image: cimg/node:14.18.2
          requires:
            - test
          context: platform-k8s
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
